

# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Testing

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Run Maven tests
      run: mvn clean
